#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FitConnectApp.Resource", IsApplication=true)]

namespace FitConnectApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090000
			public const int RpeList = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000e
			public const int buttonSize = 2130771982;
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f01000d
			public const int circleCrop = 2130771981;
			
			// aapt resource value: 0x7f01000f
			public const int colorScheme = 2130771983;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			// aapt resource value: 0x7f01000c
			public const int imageAspectRatio = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int imageAspectRatioAdjust = 2130771979;
			
			// aapt resource value: 0x7f010010
			public const int scopeUris = 2130771984;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_dark_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_light_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_shadow_end_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cardview_shadow_start_color = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_signin_btn_text_dark = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int common_google_signin_btn_text_dark_default = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_signin_btn_text_dark_disabled = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_signin_btn_text_dark_focused = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_signin_btn_text_dark_pressed = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_signin_btn_text_light = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int common_google_signin_btn_text_light_default = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_signin_btn_text_light_disabled = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_signin_btn_text_light_focused = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_signin_btn_text_light_pressed = 2131034123;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int cardview_compat_inset_shadow = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_default_elevation = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_default_radius = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Icon2 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int logo = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0030
			public const int Account = 2131361840;
			
			// aapt resource value: 0x7f0a0009
			public const int AccountTitleText = 2131361801;
			
			// aapt resource value: 0x7f0a002c
			public const int AddExDone = 2131361836;
			
			// aapt resource value: 0x7f0a0012
			public const int AddExercise = 2131361810;
			
			// aapt resource value: 0x7f0a002a
			public const int ExType = 2131361834;
			
			// aapt resource value: 0x7f0a0018
			public const int ExerciseName = 2131361816;
			
			// aapt resource value: 0x7f0a002e
			public const int Logout = 2131361838;
			
			// aapt resource value: 0x7f0a002b
			public const int MuscleGroup = 2131361835;
			
			// aapt resource value: 0x7f0a001d
			public const int SetTextView = 2131361821;
			
			// aapt resource value: 0x7f0a002f
			public const int Social = 2131361839;
			
			// aapt resource value: 0x7f0a003e
			public const int StartNewWorkoutBtn = 2131361854;
			
			// aapt resource value: 0x7f0a0032
			public const int Stats = 2131361842;
			
			// aapt resource value: 0x7f0a0041
			public const int StatsTitleText = 2131361857;
			
			// aapt resource value: 0x7f0a0033
			public const int WelcomeText = 2131361843;
			
			// aapt resource value: 0x7f0a0031
			public const int Workouts = 2131361841;
			
			// aapt resource value: 0x7f0a000a
			public const int accountUsernameText = 2131361802;
			
			// aapt resource value: 0x7f0a0028
			public const int addNote = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int addSet = 2131361833;
			
			// aapt resource value: 0x7f0a0000
			public const int adjust_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int adjust_width = 2131361793;
			
			// aapt resource value: 0x7f0a0006
			public const int auto = 2131361798;
			
			// aapt resource value: 0x7f0a0037
			public const int basic_sign_in_button = 2131361847;
			
			// aapt resource value: 0x7f0a0040
			public const int button2 = 2131361856;
			
			// aapt resource value: 0x7f0a0011
			public const int buttons = 2131361809;
			
			// aapt resource value: 0x7f0a0027
			public const int buttonspacer = 2131361831;
			
			// aapt resource value: 0x7f0a0038
			public const int create_account_button = 2131361848;
			
			// aapt resource value: 0x7f0a0007
			public const int dark = 2131361799;
			
			// aapt resource value: 0x7f0a000c
			public const int dateContainer = 2131361804;
			
			// aapt resource value: 0x7f0a0016
			public const int deleteExercise = 2131361814;
			
			// aapt resource value: 0x7f0a0019
			public const int dragElement = 2131361817;
			
			// aapt resource value: 0x7f0a001b
			public const int exDataTable = 2131361819;
			
			// aapt resource value: 0x7f0a0010
			public const int exerciseCardsFrame = 2131361808;
			
			// aapt resource value: 0x7f0a0023
			public const int exerciseControls = 2131361827;
			
			// aapt resource value: 0x7f0a0014
			public const int fragmentContainer = 2131361812;
			
			// aapt resource value: 0x7f0a0046
			public const int genderText = 2131361862;
			
			// aapt resource value: 0x7f0a0047
			public const int genderUpdateButton = 2131361863;
			
			// aapt resource value: 0x7f0a002d
			public const int gridLayout1 = 2131361837;
			
			// aapt resource value: 0x7f0a0042
			public const int heightText = 2131361858;
			
			// aapt resource value: 0x7f0a0043
			public const int heightUpdateButton = 2131361859;
			
			// aapt resource value: 0x7f0a0003
			public const int icon_only = 2131361795;
			
			// aapt resource value: 0x7f0a0008
			public const int light = 2131361800;
			
			// aapt resource value: 0x7f0a003b
			public const int linearLayout1 = 2131361851;
			
			// aapt resource value: 0x7f0a0022
			public const int linearLayout2 = 2131361826;
			
			// aapt resource value: 0x7f0a003d
			public const int listView1 = 2131361853;
			
			// aapt resource value: 0x7f0a003f
			public const int loadSavedWorkout = 2131361855;
			
			// aapt resource value: 0x7f0a0035
			public const int loginUsernameText = 2131361845;
			
			// aapt resource value: 0x7f0a0015
			public const int nameBar = 2131361813;
			
			// aapt resource value: 0x7f0a0002
			public const int none = 2131361794;
			
			// aapt resource value: 0x7f0a0021
			public const int notesTextView = 2131361825;
			
			// aapt resource value: 0x7f0a0036
			public const int passwordText = 2131361846;
			
			// aapt resource value: 0x7f0a0025
			public const int reps = 2131361829;
			
			// aapt resource value: 0x7f0a001f
			public const int repsTextView = 2131361823;
			
			// aapt resource value: 0x7f0a0026
			public const int rpeSpinner = 2131361830;
			
			// aapt resource value: 0x7f0a0020
			public const int rpeTextView = 2131361824;
			
			// aapt resource value: 0x7f0a0013
			public const int saveWorkoutBtn = 2131361811;
			
			// aapt resource value: 0x7f0a000f
			public const int scrollView1 = 2131361807;
			
			// aapt resource value: 0x7f0a0039
			public const int sign_in_button = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int sign_out_and_disconnect = 2131361850;
			
			// aapt resource value: 0x7f0a001a
			public const int space1 = 2131361818;
			
			// aapt resource value: 0x7f0a0004
			public const int standard = 2131361796;
			
			// aapt resource value: 0x7f0a0034
			public const int statusTextView = 2131361844;
			
			// aapt resource value: 0x7f0a001c
			public const int tableHeader = 2131361820;
			
			// aapt resource value: 0x7f0a003c
			public const int textView1 = 2131361852;
			
			// aapt resource value: 0x7f0a0017
			public const int topspacer = 2131361815;
			
			// aapt resource value: 0x7f0a0024
			public const int weight = 2131361828;
			
			// aapt resource value: 0x7f0a0044
			public const int weightText = 2131361860;
			
			// aapt resource value: 0x7f0a001e
			public const int weightTextView = 2131361822;
			
			// aapt resource value: 0x7f0a0045
			public const int weightUpdateButton = 2131361861;
			
			// aapt resource value: 0x7f0a0005
			public const int wide = 2131361797;
			
			// aapt resource value: 0x7f0a000d
			public const int workoutDate = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int workoutDateIcon = 2131361806;
			
			// aapt resource value: 0x7f0a000b
			public const int workoutScreen = 2131361803;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateWorkoutScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ExerciseCard = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ExerciseSelect = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HomeScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Social = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int StartWorkout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Stats = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07001c
			public const int ApiKey = 2131165212;
			
			// aapt resource value: 0x7f07001f
			public const int ApplicationId = 2131165215;
			
			// aapt resource value: 0x7f070019
			public const int ApplicationName = 2131165209;
			
			// aapt resource value: 0x7f070020
			public const int ClientId = 2131165216;
			
			// aapt resource value: 0x7f07001d
			public const int DatabaseUrl = 2131165213;
			
			// aapt resource value: 0x7f070018
			public const int Hello = 2131165208;
			
			// aapt resource value: 0x7f070021
			public const int SenderId = 2131165217;
			
			// aapt resource value: 0x7f07001e
			public const int StorageBucket = 2131165214;
			
			// aapt resource value: 0x7f070000
			public const int common_google_play_services_enable_button = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int common_google_play_services_enable_text = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_play_services_enable_title = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_google_play_services_install_button = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int common_google_play_services_install_text = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_install_title = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_notification_ticker = 2131165190;
			
			// aapt resource value: 0x7f070010
			public const int common_google_play_services_unknown_issue = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_unsupported_text = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_update_button = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_update_text = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_update_title = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_updating_text = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_wear_update_text = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int common_open_on_phone = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int common_signin_button_text = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int common_signin_button_text_long = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int default_web_client_id = 2131165203;
			
			// aapt resource value: 0x7f070023
			public const int fa_arrows = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int fa_calendar = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int fa_check = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int fa_delete = 2131165220;
			
			// aapt resource value: 0x7f070026
			public const int fa_note = 2131165222;
			
			// aapt resource value: 0x7f070014
			public const int firebase_database_url = 2131165204;
			
			// aapt resource value: 0x7f070011
			public const int gcm_defaultSenderId = 2131165201;
			
			// aapt resource value: 0x7f070015
			public const int google_api_key = 2131165205;
			
			// aapt resource value: 0x7f070012
			public const int google_app_id = 2131165202;
			
			// aapt resource value: 0x7f070016
			public const int google_crash_reporting_api_key = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int google_storage_bucket = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int signed_in_fmt = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int signed_out = 2131165211;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public const int Base_CardView = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int CardView = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int CardView_Dark = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int CardView_Light = 2130968579;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] LoadingImageView = new int[] {
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
