#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FitConnectApp.Resource", IsApplication=true)]

namespace FitConnectApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int RpeList = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int common_google_signin_btn_text_dark = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int common_google_signin_btn_text_dark_default = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int common_google_signin_btn_text_dark_disabled = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int common_google_signin_btn_text_dark_focused = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_google_signin_btn_text_dark_pressed = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int common_google_signin_btn_text_light = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int common_google_signin_btn_text_light_default = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int common_google_signin_btn_text_light_disabled = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_signin_btn_text_light_focused = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_google_signin_btn_text_light_pressed = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Icon2 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int logo = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070016
			public const int Account = 2131165206;
			
			// aapt resource value: 0x7f070009
			public const int AccountTitleText = 2131165193;
			// aapt resource value: 0x7f080028
			public const int AddExDone = 2131230760;
			
			// aapt resource value: 0x7f080010
			public const int AddExercise = 2131230736;
			
			// aapt resource value: 0x7f080026
			public const int ExType = 2131230758;
			
			// aapt resource value: 0x7f080014
			public const int ExerciseName = 2131230740;
			
			// aapt resource value: 0x7f08002a
			public const int Logout = 2131230762;
			
			// aapt resource value: 0x7f080027
			public const int MuscleGroup = 2131230759;
			
			// aapt resource value: 0x7f08001a
			public const int SetTextView = 2131230746;
			
			// aapt resource value: 0x7f08002b
			public const int Social = 2131230763;
			
			// aapt resource value: 0x7f080036
			public const int StartNewWorkoutBtn = 2131230774;
			
			// aapt resource value: 0x7f08002e
			public const int Stats = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int WelcomeText = 2131230767;
			
			// aapt resource value: 0x7f08002d
			public const int Workouts = 2131230765;
			
			// aapt resource value: 0x7f080024
			public const int addNote = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int addSet = 2131230757;
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int auto = 2131230726;
			
			// aapt resource value: 0x7f080037
			public const int button2 = 2131230775;
			
			// aapt resource value: 0x7f08000f
			public const int buttons = 2131230735;
			
			// aapt resource value: 0x7f080007
			public const int dark = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int dateContainer = 2131230730;
			
			// aapt resource value: 0x7f080015
			public const int deleteExercise = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int dragElement = 2131230742;
			
			// aapt resource value: 0x7f080018
			public const int exDataTable = 2131230744;
			
			// aapt resource value: 0x7f08000e
			public const int exerciseCardsFrame = 2131230734;
			
			// aapt resource value: 0x7f080020
			public const int exerciseControls = 2131230752;
			
			// aapt resource value: 0x7f080012
			public const int fragmentContainer = 2131230738;
			
			// aapt resource value: 0x7f080029
			public const int gridLayout1 = 2131230761;
			
			// aapt resource value: 0x7f080003
			public const int icon_only = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int light = 2131230728;
			
			// aapt resource value: 0x7f080033
			public const int linearLayout1 = 2131230771;
			
			// aapt resource value: 0x7f08001f
			public const int linearLayout2 = 2131230751;
			
			// aapt resource value: 0x7f080035
			public const int listView1 = 2131230773;
			
			// aapt resource value: 0x7f070018
			public const int Stats = 2131165208;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			// aapt resource value: 0x7f070023
			public const int StatsTitleText = 2131165219;
			
			// aapt resource value: 0x7f08001e
			public const int notesTextView = 2131230750;
			// aapt resource value: 0x7f070019
			public const int WelcomeText = 2131165209;
			
			// aapt resource value: 0x7f080022
			public const int reps = 2131230754;
			// aapt resource value: 0x7f070017
			public const int Workouts = 2131165207;
			
			// aapt resource value: 0x7f07000a
			public const int accountUsernameText = 2131165194;
			// aapt resource value: 0x7f08001c
			public const int repsTextView = 2131230748;
			
			// aapt resource value: 0x7f080023
			public const int rpeSpinner = 2131230755;
			
			// aapt resource value: 0x7f08001d
			public const int rpeTextView = 2131230749;
			
			// aapt resource value: 0x7f080011
			public const int saveWorkoutBtn = 2131230737;
			
			// aapt resource value: 0x7f07001d
			public const int basic_sign_in_button = 2131165213;
			
			// aapt resource value: 0x7f070022
			public const int button2 = 2131165218;
			
			// aapt resource value: 0x7f07000d
			public const int buttons = 2131165197;
			// aapt resource value: 0x7f08000d
			public const int scrollView1 = 2131230733;
			
			// aapt resource value: 0x7f07001e
			public const int create_account_button = 2131165214;
			// aapt resource value: 0x7f080031
			public const int sign_in_button = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int sign_out_and_disconnect = 2131230770;
			
			// aapt resource value: 0x7f080017
			public const int space1 = 2131230743;
			// aapt resource value: 0x7f07000c
			public const int exerciseCardsFrame = 2131165196;
			
			// aapt resource value: 0x7f080004
			public const int standard = 2131230724;
			// aapt resource value: 0x7f070028
			public const int genderText = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int genderUpdateButton = 2131165225;
			
			// aapt resource value: 0x7f070013
			public const int gridLayout1 = 2131165203;
			
			// aapt resource value: 0x7f070024
			public const int heightText = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int heightUpdateButton = 2131165221;
			
			// aapt resource value: 0x7f070003
			public const int icon_only = 2131165187;
			// aapt resource value: 0x7f080030
			public const int statusTextView = 2131230768;
			
			// aapt resource value: 0x7f080019
			public const int tableHeader = 2131230745;
			
			// aapt resource value: 0x7f07001b
			public const int loginUsernameText = 2131165211;
			
			// aapt resource value: 0x7f070002
			public const int none = 2131165186;
			// aapt resource value: 0x7f080034
			public const int textView1 = 2131230772;
			
			// aapt resource value: 0x7f080021
			public const int weight = 2131230753;
			// aapt resource value: 0x7f07001c
			public const int passwordText = 2131165212;
			
			// aapt resource value: 0x7f08001b
			public const int weightTextView = 2131230747;
			// aapt resource value: 0x7f07000b
			public const int scrollView1 = 2131165195;
			
			// aapt resource value: 0x7f07001f
			public const int sign_in_button = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int sign_out_and_disconnect = 2131165216;
			// aapt resource value: 0x7f080005
			public const int wide = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int workoutDate = 2131230731;
			
			// aapt resource value: 0x7f07001a
			public const int statusTextView = 2131165210;
			
			// aapt resource value: 0x7f070026
			public const int weightText = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int weightUpdateButton = 2131165223;
			// aapt resource value: 0x7f08000c
			public const int workoutDateIcon = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int workoutScreen = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateWorkoutScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ExerciseCard = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ExerciseSelect = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HomeScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Social = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int StartWorkout = 2130903046;
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int StartWorkout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Stats = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05001c
			public const int ApiKey = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int ApplicationId = 2131034143;
			
			// aapt resource value: 0x7f050019
			public const int ApplicationName = 2131034137;
			
			// aapt resource value: 0x7f050020
			public const int ClientId = 2131034144;
			
			// aapt resource value: 0x7f05001d
			public const int DatabaseUrl = 2131034141;
			
			// aapt resource value: 0x7f050018
			public const int Hello = 2131034136;
			
			// aapt resource value: 0x7f050021
			public const int SenderId = 2131034145;
			
			// aapt resource value: 0x7f05001e
			public const int StorageBucket = 2131034142;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_enable_button = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_title = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_title = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_notification_ticker = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_unknown_issue = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_unsupported_text = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_button = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_text = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_title = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_updating_text = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_wear_update_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_open_on_phone = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_signin_button_text = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text_long = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int default_web_client_id = 2131034131;
			
			// aapt resource value: 0x7f050023
			public const int fa_arrows = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int fa_calendar = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int fa_delete = 2131034148;
			
			// aapt resource value: 0x7f050014
			public const int firebase_database_url = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int gcm_defaultSenderId = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int google_api_key = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int google_app_id = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int google_crash_reporting_api_key = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int google_storage_bucket = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int signed_in_fmt = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int signed_out = 2131034139;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
