# -*- coding: utf-8 -*-
"""
Created on Mon Nov 20 01:40:17 2017

@author: Solammy
"""

class featureExtract:
    def finalGamePrep(self, dictinput, trRangeStart, trRangeEnd, valyrStart, valyrEnd,testyrStart, testyrEnd):
        retTrainingScore = []
        retTrainingScoreY = []
        retValScore = []
        retValScoreY = []
        retTestScore = []
        retTestScoreY = []
        retTrainWinner = []
        retTrainWinnerY = []
        retValWinner = []
        retValWinnerY = []
        retTestWinner = []
        retTestWinnerY = []
        for each in dictinput:
            testYear = int(float(dictinput[each]["year"]))
            if trRangeStart <= testYear <= trRangeEnd or valyrStart <= testYear <= valyrEnd or testyrStart <= testYear <= testyrEnd:
                vis = dict(dictinput[each])
                home = dict(dictinput[each])
                visY = int(float(vis["VisFinalScore"]))
                homeY = int(float(home["HomeFinalScore"]))
                winPredict = dict(dictinput[each])
                if visY > homeY:
                    winner = "Visitor"
                elif homeY > visY:
                    winner = "Home"
                else:
                    winner = "Tie"
                
               
                year = vis["year"]
                year = int(float(year))
                del vis["GameID"]
                del vis["year"]
                del vis["Date"]
                del vis["VisTeam"]
                del vis["HomeTeam"]
                del vis["StartTime"]
                del vis["GameLoc"]
                del vis["VisFinalScore"]
                del vis["HomeFinalScore"]
                del vis["VisStartPit"]
                del vis["HomeStartPit"]
                del vis["VisBat1"]
                del vis["VisBat2"]
                del vis["VisBat3"]
                del vis["VisBat4"]
                del vis["VisBat5"]
                del vis["VisBat6"]
                del vis["VisBat7"]
                del vis["VisBat8"]
                del vis["VisBat9"]
                del vis["VisBat1Pos"]
                del vis["VisBat2Pos"]
                del vis["VisBat3Pos"]
                del vis["VisBat4Pos"]
                del vis["VisBat5Pos"]
                del vis["VisBat6Pos"]
                del vis["VisBat7Pos"]
                del vis["VisBat8Pos"]
                del vis["VisBat9Pos"]
                del vis["HomeBat1"]
                del vis["HomeBat2"]
                del vis["HomeBat3"]
                del vis["HomeBat4"]
                del vis["HomeBat5"]
                del vis["HomeBat6"]
                del vis["HomeBat7"]
                del vis["HomeBat8"]
                del vis["HomeBat9"]
                del vis["HomeBat1Pos"]
                del vis["HomeBat1SeasonSO"]
                del vis["HomeBat1SeasonSingles"]
                del vis["HomeBat1SeasonDoub"]
                del vis["HomeBat1SeasonTrip"]
                del vis["HomeBat1SeasonHR"]
                del vis["HomeBat1SeasonHits"]
                del vis["HomeBat1SeasonAB"]
                del vis["HomeBat1SeasonWalk"]
                del vis["HomeBat1SeasonAVG"]
                ##5game
                del vis["HomeBat1fiveGameSO"]
                del vis["HomeBat1fiveGameSingles"]
                del vis["HomeBat1fiveGameDoub"]
                del vis["HomeBat1fiveGameTrip"]
                del vis["HomeBat1fiveGameHR"]
                del vis["HomeBat1fiveGameHits"]
                del vis["HomeBat1fiveGameAB"]
                del vis["HomeBat1fiveGameWalk"]
                del vis["HomeBat1fiveGameAVG"]
                del vis["HomeBat1gameSO"]
                del vis["HomeBat1gameSingles"]
                del vis["HomeBat1gameDoub"]
                del vis["HomeBat1gameTrip"]
                del vis["HomeBat1gameHR"]
                del vis["HomeBat1gameHits"]
                del vis["HomeBat1gameAB"]
                del vis["HomeBat1gameWalk"]
                
                del vis["HomeBat2Pos"]
                del vis["HomeBat2SeasonSO"]
                del vis["HomeBat2SeasonSingles"]
                del vis["HomeBat2SeasonDoub"]
                del vis["HomeBat2SeasonTrip"]
                del vis["HomeBat2SeasonHR"]
                del vis["HomeBat2SeasonHits"]
                del vis["HomeBat2SeasonAB"]
                del vis["HomeBat2SeasonWalk"]
                del vis["HomeBat2SeasonAVG"]
                ##5game
                del vis["HomeBat2fiveGameSO"]
                del vis["HomeBat2fiveGameSingles"]
                del vis["HomeBat2fiveGameDoub"]
                del vis["HomeBat2fiveGameTrip"]
                del vis["HomeBat2fiveGameHR"]
                del vis["HomeBat2fiveGameHits"]
                del vis["HomeBat2fiveGameAB"]
                del vis["HomeBat2fiveGameWalk"] 
                del vis["HomeBat2fiveGameAVG"]
                del vis["HomeBat2gameSO"]
                del vis["HomeBat2gameSingles"]
                del vis["HomeBat2gameDoub"]
                del vis["HomeBat2gameTrip"]
                del vis["HomeBat2gameHR"]
                del vis["HomeBat2gameHits"]
                del vis["HomeBat2gameAB"]
                del vis["HomeBat2gameWalk"]
                del vis["HomeBat3Pos"]
                del vis["HomeBat3SeasonSO"]
                del vis["HomeBat3SeasonSingles"]
                del vis["HomeBat3SeasonDoub"]
                del vis["HomeBat3SeasonTrip"]
                del vis["HomeBat3SeasonHR"]
                del vis["HomeBat3SeasonHits"]
                del vis["HomeBat3SeasonAB"]
                del vis["HomeBat3SeasonWalk"]
                del vis["HomeBat3SeasonAVG"]
                ##5game
                del vis["HomeBat3fiveGameSO"]
                del vis["HomeBat3fiveGameSingles"]
                del vis["HomeBat3fiveGameDoub"]
                del vis["HomeBat3fiveGameTrip"]
                del vis["HomeBat3fiveGameHR"]
                del vis["HomeBat3fiveGameHits"]
                del vis["HomeBat3fiveGameAB"]
                del vis["HomeBat3fiveGameWalk"]
                del vis["HomeBat3fiveGameAVG"]
                del vis["HomeBat3gameSO"]
                del vis["HomeBat3gameSingles"]
                del vis["HomeBat3gameDoub"]
                del vis["HomeBat3gameTrip"]
                del vis["HomeBat3gameHR"]
                del vis["HomeBat3gameHits"]
                del vis["HomeBat3gameAB"]
                del vis["HomeBat3gameWalk"]
                del vis["HomeBat4Pos"]
                del vis["HomeBat4SeasonSO"]
                del vis["HomeBat4SeasonSingles"]
                del vis["HomeBat4SeasonDoub"]
                del vis["HomeBat4SeasonTrip"]
                del vis["HomeBat4SeasonHR"]
                del vis["HomeBat4SeasonHits"]
                del vis["HomeBat4SeasonAB"]
                del vis["HomeBat4SeasonWalk"]
                del vis["HomeBat4SeasonAVG"]
                ##5game
                del vis["HomeBat4fiveGameSO"]
                del vis["HomeBat4fiveGameSingles"]
                del vis["HomeBat4fiveGameDoub"]
                del vis["HomeBat4fiveGameTrip"]
                del vis["HomeBat4fiveGameHR"]
                del vis["HomeBat4fiveGameHits"]
                del vis["HomeBat4fiveGameAB"]
                del vis["HomeBat4fiveGameWalk"]
                del vis["HomeBat4fiveGameAVG"]
                del vis["HomeBat4gameSO"]
                del vis["HomeBat4gameSingles"]
                del vis["HomeBat4gameDoub"]
                del vis["HomeBat4gameTrip"]
                del vis["HomeBat4gameHR"]
                del vis["HomeBat4gameHits"]
                del vis["HomeBat4gameAB"]
                del vis["HomeBat4gameWalk"]
                del vis["HomeBat5Pos"]
                del vis["HomeBat5SeasonSO"]
                del vis["HomeBat5SeasonSingles"]
                del vis["HomeBat5SeasonDoub"]
                del vis["HomeBat5SeasonTrip"]
                del vis["HomeBat5SeasonHR"]
                del vis["HomeBat5SeasonHits"]
                del vis["HomeBat5SeasonAB"]
                del vis["HomeBat5SeasonWalk"]
                del vis["HomeBat5SeasonAVG"]
                ##5game
                del vis["HomeBat5fiveGameSO"]
                del vis["HomeBat5fiveGameSingles"]
                del vis["HomeBat5fiveGameDoub"]
                del vis["HomeBat5fiveGameTrip"]
                del vis["HomeBat5fiveGameHR"]
                del vis["HomeBat5fiveGameHits"]
                del vis["HomeBat5fiveGameAB"]
                del vis["HomeBat5fiveGameWalk"]
                del vis["HomeBat5fiveGameAVG"]
                del vis["HomeBat5gameSO"]
                del vis["HomeBat5gameSingles"]
                del vis["HomeBat5gameDoub"]
                del vis["HomeBat5gameTrip"]
                del vis["HomeBat5gameHR"]
                del vis["HomeBat5gameHits"]
                del vis["HomeBat5gameAB"]
                del vis["HomeBat5gameWalk"]
                del vis["HomeBat6Pos"]
                del vis["HomeBat6SeasonSO"]
                del vis["HomeBat6SeasonSingles"]
                del vis["HomeBat6SeasonDoub"]
                del vis["HomeBat6SeasonTrip"]
                del vis["HomeBat6SeasonHR"]
                del vis["HomeBat6SeasonHits"]
                del vis["HomeBat6SeasonAB"]
                del vis["HomeBat6SeasonWalk"]
                del vis["HomeBat6SeasonAVG"]
                ##5game
                del vis["HomeBat6fiveGameSO"]
                del vis["HomeBat6fiveGameSingles"]
                del vis["HomeBat6fiveGameDoub"]
                del vis["HomeBat6fiveGameTrip"]
                del vis["HomeBat6fiveGameHR"]
                del vis["HomeBat6fiveGameHits"]
                del vis["HomeBat6fiveGameAB"]
                del vis["HomeBat6fiveGameWalk"]
                del vis["HomeBat6fiveGameAVG"]
                del vis["HomeBat6gameSO"]
                del vis["HomeBat6gameSingles"]
                del vis["HomeBat6gameDoub"]
                del vis["HomeBat6gameTrip"]
                del vis["HomeBat6gameHR"]
                del vis["HomeBat6gameHits"]
                del vis["HomeBat6gameAB"]
                del vis["HomeBat6gameWalk"]
                del vis["HomeBat7Pos"]
                del vis["HomeBat7SeasonSO"]
                del vis["HomeBat7SeasonSingles"]
                del vis["HomeBat7SeasonDoub"]
                del vis["HomeBat7SeasonTrip"]
                del vis["HomeBat7SeasonHR"]
                del vis["HomeBat7SeasonHits"]
                del vis["HomeBat7SeasonAB"]
                del vis["HomeBat7SeasonWalk"]
                del vis["HomeBat7SeasonAVG"]
                ##5game
                del vis["HomeBat7fiveGameSO"]
                del vis["HomeBat7fiveGameSingles"]
                del vis["HomeBat7fiveGameDoub"]
                del vis["HomeBat7fiveGameTrip"]
                del vis["HomeBat7fiveGameHR"]
                del vis["HomeBat7fiveGameHits"]
                del vis["HomeBat7fiveGameAB"]
                del vis["HomeBat7fiveGameWalk"]
                del vis["HomeBat7fiveGameAVG"]
                del vis["HomeBat7gameSO"]
                del vis["HomeBat7gameSingles"]
                del vis["HomeBat7gameDoub"]
                del vis["HomeBat7gameTrip"]
                del vis["HomeBat7gameHR"]
                del vis["HomeBat7gameHits"]
                del vis["HomeBat7gameAB"]
                del vis["HomeBat7gameWalk"]
                del vis["HomeBat8Pos"]
                del vis["HomeBat8SeasonSO"]
                del vis["HomeBat8SeasonSingles"]
                del vis["HomeBat8SeasonDoub"]
                del vis["HomeBat8SeasonTrip"]
                del vis["HomeBat8SeasonHR"]
                del vis["HomeBat8SeasonHits"]
                del vis["HomeBat8SeasonAB"]
                del vis["HomeBat8SeasonWalk"]
                del vis["HomeBat8SeasonAVG"]
                ##5game
                del vis["HomeBat8fiveGameSO"]
                del vis["HomeBat8fiveGameSingles"]
                del vis["HomeBat8fiveGameDoub"]
                del vis["HomeBat8fiveGameTrip"]
                del vis["HomeBat8fiveGameHR"]
                del vis["HomeBat8fiveGameHits"]
                del vis["HomeBat8fiveGameAB"]
                del vis["HomeBat8fiveGameWalk"]
                del vis["HomeBat8fiveGameAVG"]
                del vis["HomeBat8gameSO"]
                del vis["HomeBat8gameSingles"]
                del vis["HomeBat8gameDoub"]
                del vis["HomeBat8gameTrip"]
                del vis["HomeBat8gameHR"]
                del vis["HomeBat8gameHits"]
                del vis["HomeBat8gameAB"]
                del vis["HomeBat8gameWalk"]
                del vis["HomeBat9Pos"]
                del vis["HomeBat9SeasonSO"]
                del vis["HomeBat9SeasonSingles"]
                del vis["HomeBat9SeasonDoub"]
                del vis["HomeBat9SeasonTrip"]
                del vis["HomeBat9SeasonHR"]
                del vis["HomeBat9SeasonHits"]
                del vis["HomeBat9SeasonAB"]
                del vis["HomeBat9SeasonWalk"]
                del vis["HomeBat9SeasonAVG"]
                ##5game
                del vis["HomeBat9fiveGameSO"]
                del vis["HomeBat9fiveGameSingles"]
                del vis["HomeBat9fiveGameDoub"]
                del vis["HomeBat9fiveGameTrip"]
                del vis["HomeBat9fiveGameHR"]
                del vis["HomeBat9fiveGameHits"]
                del vis["HomeBat9fiveGameAB"]
                del vis["HomeBat9fiveGameWalk"]
                del vis["HomeBat9fiveGameAVG"]
                del vis["HomeBat9gameSO"]
                del vis["HomeBat9gameSingles"]
                del vis["HomeBat9gameDoub"]
                del vis["HomeBat9gameTrip"]
                del vis["HomeBat9gameHR"]
                del vis["HomeBat9gameHits"]
                del vis["HomeBat9gameAB"]
                del vis["HomeBat9gameWalk"]
                ########    HOME Side    ###################
                del home["GameID"]
                del home["year"]
                del home["Date"]
                del home["VisTeam"]
                del home["HomeTeam"]
                del home["StartTime"]
                del home["GameLoc"]
                del home["VisFinalScore"]
                del home["HomeFinalScore"]
                del home["VisStartPit"]
                del home["HomeStartPit"]
                del home["VisBat1"]
                del home["VisBat2"]
                del home["VisBat3"]
                del home["VisBat4"]
                del home["VisBat5"]
                del home["VisBat6"]
                del home["VisBat7"]
                del home["VisBat8"]
                del home["VisBat9"]
                del home["HomeBat1"]
                del home["HomeBat2"]
                del home["HomeBat3"]
                del home["HomeBat4"]
                del home["HomeBat5"]
                del home["HomeBat6"]
                del home["HomeBat7"]
                del home["HomeBat8"]
                del home["HomeBat9"]
                del home["HomeBat1Pos"]
                del home["HomeBat2Pos"]
                del home["HomeBat3Pos"]
                del home["HomeBat4Pos"]
                del home["HomeBat5Pos"]
                del home["HomeBat6Pos"]
                del home["HomeBat7Pos"]
                del home["HomeBat8Pos"]
                del home["HomeBat9Pos"]
                del home["VisBat1Pos"]
                del home["VisBat1SeasonSO"]
                del home["VisBat1SeasonSingles"]
                del home["VisBat1SeasonDoub"]
                del home["VisBat1SeasonTrip"]
                del home["VisBat1SeasonHR"]
                del home["VisBat1SeasonHits"]
                del home["VisBat1SeasonAB"]
                del home["VisBat1SeasonWalk"]
                del home["VisBat1SeasonAVG"]
                ##5game
                del home["VisBat1fiveGameSO"]
                del home["VisBat1fiveGameSingles"]
                del home["VisBat1fiveGameDoub"]
                del home["VisBat1fiveGameTrip"]
                del home["VisBat1fiveGameHR"]
                del home["VisBat1fiveGameHits"]
                del home["VisBat1fiveGameAB"]
                del home["VisBat1fiveGameWalk"]
                del home["VisBat1fiveGameAVG"]
                del home["VisBat1gameSO"]
                del home["VisBat1gameSingles"]
                del home["VisBat1gameDoub"]
                del home["VisBat1gameTrip"]
                del home["VisBat1gameHR"]
                del home["VisBat1gameHits"]
                del home["VisBat1gameAB"]
                del home["VisBat1gameWalk"]
                del home["VisBat2Pos"]
                del home["VisBat2SeasonSO"]
                del home["VisBat2SeasonSingles"]
                del home["VisBat2SeasonDoub"]
                del home["VisBat2SeasonTrip"]
                del home["VisBat2SeasonHR"]
                del home["VisBat2SeasonHits"]
                del home["VisBat2SeasonAB"]
                del home["VisBat2SeasonWalk"]
                del home["VisBat2SeasonAVG"]
                ##5game
                del home["VisBat2fiveGameSO"]
                del home["VisBat2fiveGameSingles"]
                del home["VisBat2fiveGameDoub"]
                del home["VisBat2fiveGameTrip"]
                del home["VisBat2fiveGameHR"]
                del home["VisBat2fiveGameHits"]
                del home["VisBat2fiveGameAB"]
                del home["VisBat2fiveGameWalk"]
                del home["VisBat2fiveGameAVG"]
                del home["VisBat2gameSO"]
                del home["VisBat2gameSingles"]
                del home["VisBat2gameDoub"]
                del home["VisBat2gameTrip"]
                del home["VisBat2gameHR"]
                del home["VisBat2gameHits"]
                del home["VisBat2gameAB"]
                del home["VisBat2gameWalk"]
                del home["VisBat3Pos"]
                del home["VisBat3SeasonSO"]
                del home["VisBat3SeasonSingles"]
                del home["VisBat3SeasonDoub"]
                del home["VisBat3SeasonTrip"]
                del home["VisBat3SeasonHR"]
                del home["VisBat3SeasonHits"]
                del home["VisBat3SeasonAB"]
                del home["VisBat3SeasonWalk"]
                del home["VisBat3SeasonAVG"]
                ##5game
                del home["VisBat3fiveGameSO"]
                del home["VisBat3fiveGameSingles"]
                del home["VisBat3fiveGameDoub"]
                del home["VisBat3fiveGameTrip"]
                del home["VisBat3fiveGameHR"]
                del home["VisBat3fiveGameHits"]
                del home["VisBat3fiveGameAB"]
                del home["VisBat3fiveGameWalk"]
                del home["VisBat3fiveGameAVG"]
                del home["VisBat3gameSO"]
                del home["VisBat3gameSingles"]
                del home["VisBat3gameDoub"]
                del home["VisBat3gameTrip"]
                del home["VisBat3gameHR"]
                del home["VisBat3gameHits"]
                del home["VisBat3gameAB"]
                del home["VisBat3gameWalk"]
                del home["VisBat4Pos"]
                del home["VisBat4SeasonSO"]
                del home["VisBat4SeasonSingles"]
                del home["VisBat4SeasonDoub"]
                del home["VisBat4SeasonTrip"]
                del home["VisBat4SeasonHR"]
                del home["VisBat4SeasonHits"]
                del home["VisBat4SeasonAB"]
                del home["VisBat4SeasonWalk"]
                del home["VisBat4SeasonAVG"]
                ##5game
                del home["VisBat4fiveGameSO"]
                del home["VisBat4fiveGameSingles"]
                del home["VisBat4fiveGameDoub"]
                del home["VisBat4fiveGameTrip"]
                del home["VisBat4fiveGameHR"]
                del home["VisBat4fiveGameHits"]
                del home["VisBat4fiveGameAB"]
                del home["VisBat4fiveGameWalk"]
                del home["VisBat4fiveGameAVG"]
                del home["VisBat4gameSO"]
                del home["VisBat4gameSingles"]
                del home["VisBat4gameDoub"]
                del home["VisBat4gameTrip"]
                del home["VisBat4gameHR"]
                del home["VisBat4gameHits"]
                del home["VisBat4gameAB"]
                del home["VisBat4gameWalk"]
                del home["VisBat5Pos"]
                del home["VisBat5SeasonSO"]
                del home["VisBat5SeasonSingles"]
                del home["VisBat5SeasonDoub"]
                del home["VisBat5SeasonTrip"]
                del home["VisBat5SeasonHR"]
                del home["VisBat5SeasonHits"]
                del home["VisBat5SeasonAB"]
                del home["VisBat5SeasonWalk"]
                del home["VisBat5SeasonAVG"]
                ##5game
                del home["VisBat5fiveGameSO"]
                del home["VisBat5fiveGameSingles"]
                del home["VisBat5fiveGameDoub"]
                del home["VisBat5fiveGameTrip"]
                del home["VisBat5fiveGameHR"]
                del home["VisBat5fiveGameHits"]
                del home["VisBat5fiveGameAB"]
                del home["VisBat5fiveGameWalk"]
                del home["VisBat5fiveGameAVG"]
                del home["VisBat5gameSO"]
                del home["VisBat5gameSingles"]
                del home["VisBat5gameDoub"]
                del home["VisBat5gameTrip"]
                del home["VisBat5gameHR"]
                del home["VisBat5gameHits"]
                del home["VisBat5gameAB"]
                del home["VisBat5gameWalk"]
                del home["VisBat6Pos"]
                del home["VisBat6SeasonSO"]
                del home["VisBat6SeasonSingles"]
                del home["VisBat6SeasonDoub"]
                del home["VisBat6SeasonTrip"]
                del home["VisBat6SeasonHR"]
                del home["VisBat6SeasonHits"]
                del home["VisBat6SeasonAB"]
                del home["VisBat6SeasonWalk"]
                del home["VisBat6SeasonAVG"]
                ##5game
                del home["VisBat6fiveGameSO"]
                del home["VisBat6fiveGameSingles"]
                del home["VisBat6fiveGameDoub"]
                del home["VisBat6fiveGameTrip"]
                del home["VisBat6fiveGameHR"]
                del home["VisBat6fiveGameHits"]
                del home["VisBat6fiveGameAB"]
                del home["VisBat6fiveGameWalk"]
                del home["VisBat6fiveGameAVG"]
                del home["VisBat6gameSO"]
                del home["VisBat6gameSingles"]
                del home["VisBat6gameDoub"]
                del home["VisBat6gameTrip"]
                del home["VisBat6gameHR"]
                del home["VisBat6gameHits"]
                del home["VisBat6gameAB"]
                del home["VisBat6gameWalk"]
                del home["VisBat7Pos"]
                del home["VisBat7SeasonSO"]
                del home["VisBat7SeasonSingles"]
                del home["VisBat7SeasonDoub"]
                del home["VisBat7SeasonTrip"]
                del home["VisBat7SeasonHR"]
                del home["VisBat7SeasonHits"]
                del home["VisBat7SeasonAB"]
                del home["VisBat7SeasonWalk"]
                del home["VisBat7SeasonAVG"]
                ##5game
                del home["VisBat7fiveGameSO"]
                del home["VisBat7fiveGameSingles"]
                del home["VisBat7fiveGameDoub"]
                del home["VisBat7fiveGameTrip"]
                del home["VisBat7fiveGameHR"]
                del home["VisBat7fiveGameHits"]
                del home["VisBat7fiveGameAB"]
                del home["VisBat7fiveGameWalk"]
                del home["VisBat7fiveGameAVG"]
                del home["VisBat7gameSO"]
                del home["VisBat7gameSingles"]
                del home["VisBat7gameDoub"]
                del home["VisBat7gameTrip"]
                del home["VisBat7gameHR"]
                del home["VisBat7gameHits"]
                del home["VisBat7gameAB"]
                del home["VisBat7gameWalk"]
                del home["VisBat8Pos"]
                del home["VisBat8SeasonSO"]
                del home["VisBat8SeasonSingles"]
                del home["VisBat8SeasonDoub"]
                del home["VisBat8SeasonTrip"]
                del home["VisBat8SeasonHR"]
                del home["VisBat8SeasonHits"]
                del home["VisBat8SeasonAB"]
                del home["VisBat8SeasonWalk"]
                del home["VisBat8SeasonAVG"]
                ##5game
                del home["VisBat8fiveGameSO"]
                del home["VisBat8fiveGameSingles"]
                del home["VisBat8fiveGameDoub"]
                del home["VisBat8fiveGameTrip"]
                del home["VisBat8fiveGameHR"]
                del home["VisBat8fiveGameHits"]
                del home["VisBat8fiveGameAB"]
                del home["VisBat8fiveGameWalk"]
                del home["VisBat8fiveGameAVG"]
                del home["VisBat8gameSO"]
                del home["VisBat8gameSingles"]
                del home["VisBat8gameDoub"]
                del home["VisBat8gameTrip"]
                del home["VisBat8gameHR"]
                del home["VisBat8gameHits"]
                del home["VisBat8gameAB"]
                del home["VisBat8gameWalk"]
                del home["VisBat9Pos"]
                del home["VisBat9SeasonSO"]
                del home["VisBat9SeasonSingles"]
                del home["VisBat9SeasonDoub"]
                del home["VisBat9SeasonTrip"]
                del home["VisBat9SeasonHR"]
                del home["VisBat9SeasonHits"]
                del home["VisBat9SeasonAB"]
                del home["VisBat9SeasonWalk"]
                del home["VisBat9SeasonAVG"]
                ##5game
                del home["VisBat9fiveGameSO"]
                del home["VisBat9fiveGameSingles"]
                del home["VisBat9fiveGameDoub"]
                del home["VisBat9fiveGameTrip"]
                del home["VisBat9fiveGameHR"]
                del home["VisBat9fiveGameHits"]
                del home["VisBat9fiveGameAB"]
                del home["VisBat9fiveGameWalk"]
                del home["VisBat9fiveGameAVG"]
                del home["VisBat9gameSO"]
                del home["VisBat9gameSingles"]
                del home["VisBat9gameDoub"]
                del home["VisBat9gameTrip"]
                del home["VisBat9gameHR"]
                del home["VisBat9gameHits"]
                del home["VisBat9gameAB"]
                del home["VisBat9gameWalk"]
                ##### winner predicter
                del winPredict["GameID"]
                del winPredict["year"]
                del winPredict["Date"]
                del winPredict["VisTeam"]
                del winPredict["HomeTeam"]
                del winPredict["StartTime"]
                del winPredict["GameLoc"]
                del winPredict["VisFinalScore"]
                del winPredict["HomeFinalScore"]
                del winPredict["VisStartPit"]
                del winPredict["HomeStartPit"]
                del winPredict["VisBat1"]
                del winPredict["VisBat2"]
                del winPredict["VisBat3"]
                del winPredict["VisBat4"]
                del winPredict["VisBat5"]
                del winPredict["VisBat6"]
                del winPredict["VisBat7"]
                del winPredict["VisBat8"]
                del winPredict["VisBat9"]
                del winPredict["VisBat1Pos"]
                del winPredict["VisBat2Pos"]
                del winPredict["VisBat3Pos"]
                del winPredict["VisBat4Pos"]
                del winPredict["VisBat5Pos"]
                del winPredict["VisBat6Pos"]
                del winPredict["VisBat7Pos"]
                del winPredict["VisBat8Pos"]
                del winPredict["VisBat9Pos"]
                del winPredict["HomeBat1"]
                del winPredict["HomeBat2"]
                del winPredict["HomeBat3"]
                del winPredict["HomeBat4"]
                del winPredict["HomeBat5"]
                del winPredict["HomeBat6"]
                del winPredict["HomeBat7"]
                del winPredict["HomeBat8"]
                del winPredict["HomeBat9"]
                del winPredict["HomeBat1Pos"]
                del winPredict["HomeBat2Pos"]
                del winPredict["HomeBat3Pos"]
                del winPredict["HomeBat4Pos"]
                del winPredict["HomeBat5Pos"]
                del winPredict["HomeBat6Pos"]
                del winPredict["HomeBat7Pos"]
                del winPredict["HomeBat8Pos"]
                del winPredict["HomeBat9Pos"]
                
                if testyrStart <= year <= testyrEnd:
                    retTestScore.append(vis)
                    retTestScore.append(home)
                    retTestWinner.append(winPredict)
                    retTestScoreY.append(visY)
                    retTestScoreY.append(homeY)
                    retTestWinnerY.append(winner)
                elif valyrStart <= year <= valyrEnd:
                    retValScore.append(vis)
                    retValScore.append(home)
                    retValWinner.append(winPredict)
                    retValScoreY.append(visY)
                    retValScoreY.append(homeY)
                    retValWinnerY.append(winner)
                else:
                    retTrainingScore.append(vis)
                    retTrainingScore.append(home)
                    retTrainWinner.append(winPredict)
                    retTrainingScoreY.append(visY)
                    retTrainingScoreY.append(homeY)
                    retTrainWinnerY.append(winner)
                    
        return retTrainingScore, retTrainingScoreY, retValScore, retValScoreY, retTestScore, retTestScoreY, retTrainWinner, retTrainWinnerY, retValWinner, retValWinnerY, retTestWinner, retTestWinnerY
    
    def finalSeasonPrep(self, eventExample):
        temp = eventExample
        temp2 = []
        temp2.append(temp["GameID"])
        temp2.append(temp["batter"])
        temp2.append(temp["year"])
        temp2.append(temp["battingPos"])
        del temp["GameID"]
        del temp["Date"]
        del temp["StartTime"]
        del temp["GameLoc"]
        del temp["VisStartPit"]
        del temp["HomeStartPit"]
        del temp["batter"]
        del temp["batterHand"]
        del temp["DayNight"]
        del temp["defPos"]
        del temp['battingPos']
        del temp["year"]
        del temp["gameSO"]
        del temp["gameSingles"]
        del temp["gameDoub"]
        del temp["gameTrip"]
        del temp["gameHR"]
        del temp["gameHits"]
        del temp["gameAB"]
        del temp["gameWalk"]
        
        return temp, temp2
    def featurePlayerPrep(self, dictinput, trStart, trEnd, valStart, valEnd, testStart, testEnd, attribute):
        retTraining = []
        retTrainingY = []
        retVal = []
        retValY = []
        retTest = []
        retTestY = []
        for each in dictinput:
            testyear = int(float(dictinput[each]["year"]))
            temp = dictinput[each]
            Y = (int(float(temp[attribute])))
            del temp["GameID"]
            del temp["Date"]
            del temp["StartTime"]
            del temp["GameLoc"]
            del temp["VisStartPit"]
            del temp["HomeStartPit"]
            del temp["batter"]
            del temp["batterHand"]
            del temp["DayNight"]
            del temp["defPos"]
            del temp['battingPos']
            del temp["year"]
            del temp["gameSO"]
            del temp["gameSingles"]
            del temp["gameDoub"]
            del temp["gameTrip"]
            del temp["gameHR"]
            del temp["gameHits"]
            del temp["gameAB"]
            del temp["gameWalk"]
            
            if testStart <= testyear <= testEnd:
                retTest.append(temp)
                retTestY.append(Y)
            elif valStart <= testyear <= valEnd:
                retVal.append(temp)
                retValY.append(Y)
            else:
                retTraining.append(temp)
                retTrainingY.append(Y)
        return retTraining, retTrainingY, retVal, retValY, retTest, retTestY
                
    
    def featureSnWPrep(self, dictinput, trRangeStart, trRangeEnd, valyrStart, valyrEnd,testyrStart, testyrEnd):
        retTrainingScore = []
        retTrainingScoreY = []
        retValScore = []
        retValScoreY = []
        retTestScore = []
        retTestScoreY = []
        retTrainWinner = []
        retTrainWinnerY = []
        retValWinner = []
        retValWinnerY = []
        retTestWinner = []
        retTestWinnerY = []
        for each in dictinput:
            testYear = int(float(dictinput[each]["year"]))
            if trRangeStart <= testYear <= trRangeEnd or valyrStart <= testYear <= valyrEnd or testyrStart <= testYear <= testyrEnd:
                vis = dict(dictinput[each])
                home = dict(dictinput[each])
                visY = int(float(vis["VisFinalScore"]))
                homeY = int(float(home["HomeFinalScore"]))
                winPredict = dict(dictinput[each])
                if visY > homeY:
                    winner = "Visitor"
                elif homeY > visY:
                    winner = "Home"
                else:
                    winner = "Tie"
                
               
                year = vis["year"]
                year = int(float(year))
                del vis["GameID"]
                del vis["year"]
                del vis["Date"]
                del vis["VisTeam"]
                del vis["HomeTeam"]
                del vis["StartTime"]
                del vis["GameLoc"]
                del vis["VisFinalScore"]
                del vis["HomeFinalScore"]
                del vis["VisStartPit"]
                del vis["HomeStartPit"]
                del vis["VisBat1"]
                del vis["VisBat1gameSO"]
                del vis["VisBat1gameSingles"]
                del vis["VisBat1gameDoub"]
                del vis["VisBat1gameTrip"]
                del vis["VisBat1gameHR"]
                del vis["VisBat1gameHits"]
                del vis["VisBat1gameAB"]
                del vis["VisBat1gameWalk"]
                del vis["VisBat2"]
                del vis["VisBat2gameSO"]
                del vis["VisBat2gameSingles"]
                del vis["VisBat2gameDoub"]
                del vis["VisBat2gameTrip"]
                del vis["VisBat2gameHR"]
                del vis["VisBat2gameHits"]
                del vis["VisBat2gameAB"]
                del vis["VisBat2gameWalk"]
                del vis["VisBat3"]
                del vis["VisBat3gameSO"]
                del vis["VisBat3gameSingles"]
                del vis["VisBat3gameDoub"]
                del vis["VisBat3gameTrip"]
                del vis["VisBat3gameHR"]
                del vis["VisBat3gameHits"]
                del vis["VisBat3gameAB"]
                del vis["VisBat3gameWalk"]
                del vis["VisBat4"]
                del vis["VisBat4gameSO"]
                del vis["VisBat4gameSingles"]
                del vis["VisBat4gameDoub"]
                del vis["VisBat4gameTrip"]
                del vis["VisBat4gameHR"]
                del vis["VisBat4gameHits"]
                del vis["VisBat4gameAB"]
                del vis["VisBat4gameWalk"]
                del vis["VisBat5"]
                del vis["VisBat5gameSO"]
                del vis["VisBat5gameSingles"]
                del vis["VisBat5gameDoub"]
                del vis["VisBat5gameTrip"]
                del vis["VisBat5gameHR"]
                del vis["VisBat5gameHits"]
                del vis["VisBat5gameAB"]
                del vis["VisBat5gameWalk"]
                del vis["VisBat6"]
                del vis["VisBat6gameSO"]
                del vis["VisBat6gameSingles"]
                del vis["VisBat6gameDoub"]
                del vis["VisBat6gameTrip"]
                del vis["VisBat6gameHR"]
                del vis["VisBat6gameHits"]
                del vis["VisBat6gameAB"]
                del vis["VisBat6gameWalk"]
                del vis["VisBat7"]
                del vis["VisBat7gameSO"]
                del vis["VisBat7gameSingles"]
                del vis["VisBat7gameDoub"]
                del vis["VisBat7gameTrip"]
                del vis["VisBat7gameHR"]
                del vis["VisBat7gameHits"]
                del vis["VisBat7gameAB"]
                del vis["VisBat7gameWalk"]
                del vis["VisBat8"]
                del vis["VisBat8gameSO"]
                del vis["VisBat8gameSingles"]
                del vis["VisBat8gameDoub"]
                del vis["VisBat8gameTrip"]
                del vis["VisBat8gameHR"]
                del vis["VisBat8gameHits"]
                del vis["VisBat8gameAB"]
                del vis["VisBat8gameWalk"]
                del vis["VisBat9"]
                del vis["VisBat9gameSO"]
                del vis["VisBat9gameSingles"]
                del vis["VisBat9gameDoub"]
                del vis["VisBat9gameTrip"]
                del vis["VisBat9gameHR"]
                del vis["VisBat9gameHits"]
                del vis["VisBat9gameAB"]
                del vis["VisBat9gameWalk"]
                del vis["VisBat1Pos"]
                del vis["VisBat2Pos"]
                del vis["VisBat3Pos"]
                del vis["VisBat4Pos"]
                del vis["VisBat5Pos"]
                del vis["VisBat6Pos"]
                del vis["VisBat7Pos"]
                del vis["VisBat8Pos"]
                del vis["VisBat9Pos"]
                del vis["HomeBat1"]
                del vis["HomeBat2"]
                del vis["HomeBat3"]
                del vis["HomeBat4"]
                del vis["HomeBat5"]
                del vis["HomeBat6"]
                del vis["HomeBat7"]
                del vis["HomeBat8"]
                del vis["HomeBat9"]
                del vis["HomeBat1Pos"]
                del vis["HomeBat1SeasonSO"]
                del vis["HomeBat1SeasonSingles"]
                del vis["HomeBat1SeasonDoub"]
                del vis["HomeBat1SeasonTrip"]
                del vis["HomeBat1SeasonHR"]
                del vis["HomeBat1SeasonHits"]
                del vis["HomeBat1SeasonAB"]
                del vis["HomeBat1SeasonWalk"]
                del vis["HomeBat1SeasonAVG"]
                ##5game
                del vis["HomeBat1fiveGameSO"]
                del vis["HomeBat1fiveGameSingles"]
                del vis["HomeBat1fiveGameDoub"]
                del vis["HomeBat1fiveGameTrip"]
                del vis["HomeBat1fiveGameHR"]
                del vis["HomeBat1fiveGameHits"]
                del vis["HomeBat1fiveGameAB"]
                del vis["HomeBat1fiveGameWalk"]
                del vis["HomeBat1fiveGameAVG"]
                del vis["HomeBat1gameSO"]
                del vis["HomeBat1gameSingles"]
                del vis["HomeBat1gameDoub"]
                del vis["HomeBat1gameTrip"]
                del vis["HomeBat1gameHR"]
                del vis["HomeBat1gameHits"]
                del vis["HomeBat1gameAB"]
                del vis["HomeBat1gameWalk"]
                
                del vis["HomeBat2Pos"]
                del vis["HomeBat2SeasonSO"]
                del vis["HomeBat2SeasonSingles"]
                del vis["HomeBat2SeasonDoub"]
                del vis["HomeBat2SeasonTrip"]
                del vis["HomeBat2SeasonHR"]
                del vis["HomeBat2SeasonHits"]
                del vis["HomeBat2SeasonAB"]
                del vis["HomeBat2SeasonWalk"]
                del vis["HomeBat2SeasonAVG"]
                ##5game
                del vis["HomeBat2fiveGameSO"]
                del vis["HomeBat2fiveGameSingles"]
                del vis["HomeBat2fiveGameDoub"]
                del vis["HomeBat2fiveGameTrip"]
                del vis["HomeBat2fiveGameHR"]
                del vis["HomeBat2fiveGameHits"]
                del vis["HomeBat2fiveGameAB"]
                del vis["HomeBat2fiveGameWalk"] 
                del vis["HomeBat2fiveGameAVG"]
                del vis["HomeBat2gameSO"]
                del vis["HomeBat2gameSingles"]
                del vis["HomeBat2gameDoub"]
                del vis["HomeBat2gameTrip"]
                del vis["HomeBat2gameHR"]
                del vis["HomeBat2gameHits"]
                del vis["HomeBat2gameAB"]
                del vis["HomeBat2gameWalk"]
                del vis["HomeBat3Pos"]
                del vis["HomeBat3SeasonSO"]
                del vis["HomeBat3SeasonSingles"]
                del vis["HomeBat3SeasonDoub"]
                del vis["HomeBat3SeasonTrip"]
                del vis["HomeBat3SeasonHR"]
                del vis["HomeBat3SeasonHits"]
                del vis["HomeBat3SeasonAB"]
                del vis["HomeBat3SeasonWalk"]
                del vis["HomeBat3SeasonAVG"]
                ##5game
                del vis["HomeBat3fiveGameSO"]
                del vis["HomeBat3fiveGameSingles"]
                del vis["HomeBat3fiveGameDoub"]
                del vis["HomeBat3fiveGameTrip"]
                del vis["HomeBat3fiveGameHR"]
                del vis["HomeBat3fiveGameHits"]
                del vis["HomeBat3fiveGameAB"]
                del vis["HomeBat3fiveGameWalk"]
                del vis["HomeBat3fiveGameAVG"]
                del vis["HomeBat3gameSO"]
                del vis["HomeBat3gameSingles"]
                del vis["HomeBat3gameDoub"]
                del vis["HomeBat3gameTrip"]
                del vis["HomeBat3gameHR"]
                del vis["HomeBat3gameHits"]
                del vis["HomeBat3gameAB"]
                del vis["HomeBat3gameWalk"]
                del vis["HomeBat4Pos"]
                del vis["HomeBat4SeasonSO"]
                del vis["HomeBat4SeasonSingles"]
                del vis["HomeBat4SeasonDoub"]
                del vis["HomeBat4SeasonTrip"]
                del vis["HomeBat4SeasonHR"]
                del vis["HomeBat4SeasonHits"]
                del vis["HomeBat4SeasonAB"]
                del vis["HomeBat4SeasonWalk"]
                del vis["HomeBat4SeasonAVG"]
                ##5game
                del vis["HomeBat4fiveGameSO"]
                del vis["HomeBat4fiveGameSingles"]
                del vis["HomeBat4fiveGameDoub"]
                del vis["HomeBat4fiveGameTrip"]
                del vis["HomeBat4fiveGameHR"]
                del vis["HomeBat4fiveGameHits"]
                del vis["HomeBat4fiveGameAB"]
                del vis["HomeBat4fiveGameWalk"]
                del vis["HomeBat4fiveGameAVG"]
                del vis["HomeBat4gameSO"]
                del vis["HomeBat4gameSingles"]
                del vis["HomeBat4gameDoub"]
                del vis["HomeBat4gameTrip"]
                del vis["HomeBat4gameHR"]
                del vis["HomeBat4gameHits"]
                del vis["HomeBat4gameAB"]
                del vis["HomeBat4gameWalk"]
                del vis["HomeBat5Pos"]
                del vis["HomeBat5SeasonSO"]
                del vis["HomeBat5SeasonSingles"]
                del vis["HomeBat5SeasonDoub"]
                del vis["HomeBat5SeasonTrip"]
                del vis["HomeBat5SeasonHR"]
                del vis["HomeBat5SeasonHits"]
                del vis["HomeBat5SeasonAB"]
                del vis["HomeBat5SeasonWalk"]
                del vis["HomeBat5SeasonAVG"]
                ##5game
                del vis["HomeBat5fiveGameSO"]
                del vis["HomeBat5fiveGameSingles"]
                del vis["HomeBat5fiveGameDoub"]
                del vis["HomeBat5fiveGameTrip"]
                del vis["HomeBat5fiveGameHR"]
                del vis["HomeBat5fiveGameHits"]
                del vis["HomeBat5fiveGameAB"]
                del vis["HomeBat5fiveGameWalk"]
                del vis["HomeBat5fiveGameAVG"]
                del vis["HomeBat5gameSO"]
                del vis["HomeBat5gameSingles"]
                del vis["HomeBat5gameDoub"]
                del vis["HomeBat5gameTrip"]
                del vis["HomeBat5gameHR"]
                del vis["HomeBat5gameHits"]
                del vis["HomeBat5gameAB"]
                del vis["HomeBat5gameWalk"]
                del vis["HomeBat6Pos"]
                del vis["HomeBat6SeasonSO"]
                del vis["HomeBat6SeasonSingles"]
                del vis["HomeBat6SeasonDoub"]
                del vis["HomeBat6SeasonTrip"]
                del vis["HomeBat6SeasonHR"]
                del vis["HomeBat6SeasonHits"]
                del vis["HomeBat6SeasonAB"]
                del vis["HomeBat6SeasonWalk"]
                del vis["HomeBat6SeasonAVG"]
                ##5game
                del vis["HomeBat6fiveGameSO"]
                del vis["HomeBat6fiveGameSingles"]
                del vis["HomeBat6fiveGameDoub"]
                del vis["HomeBat6fiveGameTrip"]
                del vis["HomeBat6fiveGameHR"]
                del vis["HomeBat6fiveGameHits"]
                del vis["HomeBat6fiveGameAB"]
                del vis["HomeBat6fiveGameWalk"]
                del vis["HomeBat6fiveGameAVG"]
                del vis["HomeBat6gameSO"]
                del vis["HomeBat6gameSingles"]
                del vis["HomeBat6gameDoub"]
                del vis["HomeBat6gameTrip"]
                del vis["HomeBat6gameHR"]
                del vis["HomeBat6gameHits"]
                del vis["HomeBat6gameAB"]
                del vis["HomeBat6gameWalk"]
                del vis["HomeBat7Pos"]
                del vis["HomeBat7SeasonSO"]
                del vis["HomeBat7SeasonSingles"]
                del vis["HomeBat7SeasonDoub"]
                del vis["HomeBat7SeasonTrip"]
                del vis["HomeBat7SeasonHR"]
                del vis["HomeBat7SeasonHits"]
                del vis["HomeBat7SeasonAB"]
                del vis["HomeBat7SeasonWalk"]
                del vis["HomeBat7SeasonAVG"]
                ##5game
                del vis["HomeBat7fiveGameSO"]
                del vis["HomeBat7fiveGameSingles"]
                del vis["HomeBat7fiveGameDoub"]
                del vis["HomeBat7fiveGameTrip"]
                del vis["HomeBat7fiveGameHR"]
                del vis["HomeBat7fiveGameHits"]
                del vis["HomeBat7fiveGameAB"]
                del vis["HomeBat7fiveGameWalk"]
                del vis["HomeBat7fiveGameAVG"]
                del vis["HomeBat7gameSO"]
                del vis["HomeBat7gameSingles"]
                del vis["HomeBat7gameDoub"]
                del vis["HomeBat7gameTrip"]
                del vis["HomeBat7gameHR"]
                del vis["HomeBat7gameHits"]
                del vis["HomeBat7gameAB"]
                del vis["HomeBat7gameWalk"]
                del vis["HomeBat8Pos"]
                del vis["HomeBat8SeasonSO"]
                del vis["HomeBat8SeasonSingles"]
                del vis["HomeBat8SeasonDoub"]
                del vis["HomeBat8SeasonTrip"]
                del vis["HomeBat8SeasonHR"]
                del vis["HomeBat8SeasonHits"]
                del vis["HomeBat8SeasonAB"]
                del vis["HomeBat8SeasonWalk"]
                del vis["HomeBat8SeasonAVG"]
                ##5game
                del vis["HomeBat8fiveGameSO"]
                del vis["HomeBat8fiveGameSingles"]
                del vis["HomeBat8fiveGameDoub"]
                del vis["HomeBat8fiveGameTrip"]
                del vis["HomeBat8fiveGameHR"]
                del vis["HomeBat8fiveGameHits"]
                del vis["HomeBat8fiveGameAB"]
                del vis["HomeBat8fiveGameWalk"]
                del vis["HomeBat8fiveGameAVG"]
                del vis["HomeBat8gameSO"]
                del vis["HomeBat8gameSingles"]
                del vis["HomeBat8gameDoub"]
                del vis["HomeBat8gameTrip"]
                del vis["HomeBat8gameHR"]
                del vis["HomeBat8gameHits"]
                del vis["HomeBat8gameAB"]
                del vis["HomeBat8gameWalk"]
                del vis["HomeBat9Pos"]
                del vis["HomeBat9SeasonSO"]
                del vis["HomeBat9SeasonSingles"]
                del vis["HomeBat9SeasonDoub"]
                del vis["HomeBat9SeasonTrip"]
                del vis["HomeBat9SeasonHR"]
                del vis["HomeBat9SeasonHits"]
                del vis["HomeBat9SeasonAB"]
                del vis["HomeBat9SeasonWalk"]
                del vis["HomeBat9SeasonAVG"]
                ##5game
                del vis["HomeBat9fiveGameSO"]
                del vis["HomeBat9fiveGameSingles"]
                del vis["HomeBat9fiveGameDoub"]
                del vis["HomeBat9fiveGameTrip"]
                del vis["HomeBat9fiveGameHR"]
                del vis["HomeBat9fiveGameHits"]
                del vis["HomeBat9fiveGameAB"]
                del vis["HomeBat9fiveGameWalk"]
                del vis["HomeBat9fiveGameAVG"]
                del vis["HomeBat9gameSO"]
                del vis["HomeBat9gameSingles"]
                del vis["HomeBat9gameDoub"]
                del vis["HomeBat9gameTrip"]
                del vis["HomeBat9gameHR"]
                del vis["HomeBat9gameHits"]
                del vis["HomeBat9gameAB"]
                del vis["HomeBat9gameWalk"]
                ########    HOME Side    ###################
                del home["GameID"]
                del home["year"]
                del home["Date"]
                del home["VisTeam"]
                del home["HomeTeam"]
                del home["StartTime"]
                del home["GameLoc"]
                del home["VisFinalScore"]
                del home["HomeFinalScore"]
                del home["VisStartPit"]
                del home["HomeStartPit"]
                del home["VisBat1"]
                del home["VisBat2"]
                del home["VisBat3"]
                del home["VisBat4"]
                del home["VisBat5"]
                del home["VisBat6"]
                del home["VisBat7"]
                del home["VisBat8"]
                del home["VisBat9"]
                del home["HomeBat1"]
                del home["HomeBat1gameSO"]
                del home["HomeBat1gameSingles"]
                del home["HomeBat1gameDoub"]
                del home["HomeBat1gameTrip"]
                del home["HomeBat1gameHR"]
                del home["HomeBat1gameHits"]
                del home["HomeBat1gameAB"]
                del home["HomeBat1gameWalk"]
                del home["HomeBat2"]
                del home["HomeBat2gameSO"]
                del home["HomeBat2gameSingles"]
                del home["HomeBat2gameDoub"]
                del home["HomeBat2gameTrip"]
                del home["HomeBat2gameHR"]
                del home["HomeBat2gameHits"]
                del home["HomeBat2gameAB"]
                del home["HomeBat2gameWalk"]
                del home["HomeBat3"]
                del home["HomeBat3gameSO"]
                del home["HomeBat3gameSingles"]
                del home["HomeBat3gameDoub"]
                del home["HomeBat3gameTrip"]
                del home["HomeBat3gameHR"]
                del home["HomeBat3gameHits"]
                del home["HomeBat3gameAB"]
                del home["HomeBat3gameWalk"]
                del home["HomeBat4"]
                del home["HomeBat4gameSO"]
                del home["HomeBat4gameSingles"]
                del home["HomeBat4gameDoub"]
                del home["HomeBat4gameTrip"]
                del home["HomeBat4gameHR"]
                del home["HomeBat4gameHits"]
                del home["HomeBat4gameAB"]
                del home["HomeBat4gameWalk"]
                del home["HomeBat5"]
                del home["HomeBat5gameSO"]
                del home["HomeBat5gameSingles"]
                del home["HomeBat5gameDoub"]
                del home["HomeBat5gameTrip"]
                del home["HomeBat5gameHR"]
                del home["HomeBat5gameHits"]
                del home["HomeBat5gameAB"]
                del home["HomeBat5gameWalk"]
                del home["HomeBat6"]
                del home["HomeBat6gameSO"]
                del home["HomeBat6gameSingles"]
                del home["HomeBat6gameDoub"]
                del home["HomeBat6gameTrip"]
                del home["HomeBat6gameHR"]
                del home["HomeBat6gameHits"]
                del home["HomeBat6gameAB"]
                del home["HomeBat6gameWalk"]
                del home["HomeBat7"]
                del home["HomeBat7gameSO"]
                del home["HomeBat7gameSingles"]
                del home["HomeBat7gameDoub"]
                del home["HomeBat7gameTrip"]
                del home["HomeBat7gameHR"]
                del home["HomeBat7gameHits"]
                del home["HomeBat7gameAB"]
                del home["HomeBat7gameWalk"]
                del home["HomeBat8"]
                del home["HomeBat8gameSO"]
                del home["HomeBat8gameSingles"]
                del home["HomeBat8gameDoub"]
                del home["HomeBat8gameTrip"]
                del home["HomeBat8gameHR"]
                del home["HomeBat8gameHits"]
                del home["HomeBat8gameAB"]
                del home["HomeBat8gameWalk"]
                del home["HomeBat9"]
                del home["HomeBat9gameSO"]
                del home["HomeBat9gameSingles"]
                del home["HomeBat9gameDoub"]
                del home["HomeBat9gameTrip"]
                del home["HomeBat9gameHR"]
                del home["HomeBat9gameHits"]
                del home["HomeBat9gameAB"]
                del home["HomeBat9gameWalk"]
                del home["HomeBat1Pos"]
                del home["HomeBat2Pos"]
                del home["HomeBat3Pos"]
                del home["HomeBat4Pos"]
                del home["HomeBat5Pos"]
                del home["HomeBat6Pos"]
                del home["HomeBat7Pos"]
                del home["HomeBat8Pos"]
                del home["HomeBat9Pos"]
                del home["VisBat1Pos"]
                del home["VisBat1SeasonSO"]
                del home["VisBat1SeasonSingles"]
                del home["VisBat1SeasonDoub"]
                del home["VisBat1SeasonTrip"]
                del home["VisBat1SeasonHR"]
                del home["VisBat1SeasonHits"]
                del home["VisBat1SeasonAB"]
                del home["VisBat1SeasonWalk"]
                del home["VisBat1SeasonAVG"]
                ##5game
                del home["VisBat1fiveGameSO"]
                del home["VisBat1fiveGameSingles"]
                del home["VisBat1fiveGameDoub"]
                del home["VisBat1fiveGameTrip"]
                del home["VisBat1fiveGameHR"]
                del home["VisBat1fiveGameHits"]
                del home["VisBat1fiveGameAB"]
                del home["VisBat1fiveGameWalk"]
                del home["VisBat1fiveGameAVG"]
                del home["VisBat1gameSO"]
                del home["VisBat1gameSingles"]
                del home["VisBat1gameDoub"]
                del home["VisBat1gameTrip"]
                del home["VisBat1gameHR"]
                del home["VisBat1gameHits"]
                del home["VisBat1gameAB"]
                del home["VisBat1gameWalk"]
                del home["VisBat2Pos"]
                del home["VisBat2SeasonSO"]
                del home["VisBat2SeasonSingles"]
                del home["VisBat2SeasonDoub"]
                del home["VisBat2SeasonTrip"]
                del home["VisBat2SeasonHR"]
                del home["VisBat2SeasonHits"]
                del home["VisBat2SeasonAB"]
                del home["VisBat2SeasonWalk"]
                del home["VisBat2SeasonAVG"]
                ##5game
                del home["VisBat2fiveGameSO"]
                del home["VisBat2fiveGameSingles"]
                del home["VisBat2fiveGameDoub"]
                del home["VisBat2fiveGameTrip"]
                del home["VisBat2fiveGameHR"]
                del home["VisBat2fiveGameHits"]
                del home["VisBat2fiveGameAB"]
                del home["VisBat2fiveGameWalk"]
                del home["VisBat2fiveGameAVG"]
                del home["VisBat2gameSO"]
                del home["VisBat2gameSingles"]
                del home["VisBat2gameDoub"]
                del home["VisBat2gameTrip"]
                del home["VisBat2gameHR"]
                del home["VisBat2gameHits"]
                del home["VisBat2gameAB"]
                del home["VisBat2gameWalk"]
                del home["VisBat3Pos"]
                del home["VisBat3SeasonSO"]
                del home["VisBat3SeasonSingles"]
                del home["VisBat3SeasonDoub"]
                del home["VisBat3SeasonTrip"]
                del home["VisBat3SeasonHR"]
                del home["VisBat3SeasonHits"]
                del home["VisBat3SeasonAB"]
                del home["VisBat3SeasonWalk"]
                del home["VisBat3SeasonAVG"]
                ##5game
                del home["VisBat3fiveGameSO"]
                del home["VisBat3fiveGameSingles"]
                del home["VisBat3fiveGameDoub"]
                del home["VisBat3fiveGameTrip"]
                del home["VisBat3fiveGameHR"]
                del home["VisBat3fiveGameHits"]
                del home["VisBat3fiveGameAB"]
                del home["VisBat3fiveGameWalk"]
                del home["VisBat3fiveGameAVG"]
                del home["VisBat3gameSO"]
                del home["VisBat3gameSingles"]
                del home["VisBat3gameDoub"]
                del home["VisBat3gameTrip"]
                del home["VisBat3gameHR"]
                del home["VisBat3gameHits"]
                del home["VisBat3gameAB"]
                del home["VisBat3gameWalk"]
                del home["VisBat4Pos"]
                del home["VisBat4SeasonSO"]
                del home["VisBat4SeasonSingles"]
                del home["VisBat4SeasonDoub"]
                del home["VisBat4SeasonTrip"]
                del home["VisBat4SeasonHR"]
                del home["VisBat4SeasonHits"]
                del home["VisBat4SeasonAB"]
                del home["VisBat4SeasonWalk"]
                del home["VisBat4SeasonAVG"]
                ##5game
                del home["VisBat4fiveGameSO"]
                del home["VisBat4fiveGameSingles"]
                del home["VisBat4fiveGameDoub"]
                del home["VisBat4fiveGameTrip"]
                del home["VisBat4fiveGameHR"]
                del home["VisBat4fiveGameHits"]
                del home["VisBat4fiveGameAB"]
                del home["VisBat4fiveGameWalk"]
                del home["VisBat4fiveGameAVG"]
                del home["VisBat4gameSO"]
                del home["VisBat4gameSingles"]
                del home["VisBat4gameDoub"]
                del home["VisBat4gameTrip"]
                del home["VisBat4gameHR"]
                del home["VisBat4gameHits"]
                del home["VisBat4gameAB"]
                del home["VisBat4gameWalk"]
                del home["VisBat5Pos"]
                del home["VisBat5SeasonSO"]
                del home["VisBat5SeasonSingles"]
                del home["VisBat5SeasonDoub"]
                del home["VisBat5SeasonTrip"]
                del home["VisBat5SeasonHR"]
                del home["VisBat5SeasonHits"]
                del home["VisBat5SeasonAB"]
                del home["VisBat5SeasonWalk"]
                del home["VisBat5SeasonAVG"]
                ##5game
                del home["VisBat5fiveGameSO"]
                del home["VisBat5fiveGameSingles"]
                del home["VisBat5fiveGameDoub"]
                del home["VisBat5fiveGameTrip"]
                del home["VisBat5fiveGameHR"]
                del home["VisBat5fiveGameHits"]
                del home["VisBat5fiveGameAB"]
                del home["VisBat5fiveGameWalk"]
                del home["VisBat5fiveGameAVG"]
                del home["VisBat5gameSO"]
                del home["VisBat5gameSingles"]
                del home["VisBat5gameDoub"]
                del home["VisBat5gameTrip"]
                del home["VisBat5gameHR"]
                del home["VisBat5gameHits"]
                del home["VisBat5gameAB"]
                del home["VisBat5gameWalk"]
                del home["VisBat6Pos"]
                del home["VisBat6SeasonSO"]
                del home["VisBat6SeasonSingles"]
                del home["VisBat6SeasonDoub"]
                del home["VisBat6SeasonTrip"]
                del home["VisBat6SeasonHR"]
                del home["VisBat6SeasonHits"]
                del home["VisBat6SeasonAB"]
                del home["VisBat6SeasonWalk"]
                del home["VisBat6SeasonAVG"]
                ##5game
                del home["VisBat6fiveGameSO"]
                del home["VisBat6fiveGameSingles"]
                del home["VisBat6fiveGameDoub"]
                del home["VisBat6fiveGameTrip"]
                del home["VisBat6fiveGameHR"]
                del home["VisBat6fiveGameHits"]
                del home["VisBat6fiveGameAB"]
                del home["VisBat6fiveGameWalk"]
                del home["VisBat6fiveGameAVG"]
                del home["VisBat6gameSO"]
                del home["VisBat6gameSingles"]
                del home["VisBat6gameDoub"]
                del home["VisBat6gameTrip"]
                del home["VisBat6gameHR"]
                del home["VisBat6gameHits"]
                del home["VisBat6gameAB"]
                del home["VisBat6gameWalk"]
                del home["VisBat7Pos"]
                del home["VisBat7SeasonSO"]
                del home["VisBat7SeasonSingles"]
                del home["VisBat7SeasonDoub"]
                del home["VisBat7SeasonTrip"]
                del home["VisBat7SeasonHR"]
                del home["VisBat7SeasonHits"]
                del home["VisBat7SeasonAB"]
                del home["VisBat7SeasonWalk"]
                del home["VisBat7SeasonAVG"]
                ##5game
                del home["VisBat7fiveGameSO"]
                del home["VisBat7fiveGameSingles"]
                del home["VisBat7fiveGameDoub"]
                del home["VisBat7fiveGameTrip"]
                del home["VisBat7fiveGameHR"]
                del home["VisBat7fiveGameHits"]
                del home["VisBat7fiveGameAB"]
                del home["VisBat7fiveGameWalk"]
                del home["VisBat7fiveGameAVG"]
                del home["VisBat7gameSO"]
                del home["VisBat7gameSingles"]
                del home["VisBat7gameDoub"]
                del home["VisBat7gameTrip"]
                del home["VisBat7gameHR"]
                del home["VisBat7gameHits"]
                del home["VisBat7gameAB"]
                del home["VisBat7gameWalk"]
                del home["VisBat8Pos"]
                del home["VisBat8SeasonSO"]
                del home["VisBat8SeasonSingles"]
                del home["VisBat8SeasonDoub"]
                del home["VisBat8SeasonTrip"]
                del home["VisBat8SeasonHR"]
                del home["VisBat8SeasonHits"]
                del home["VisBat8SeasonAB"]
                del home["VisBat8SeasonWalk"]
                del home["VisBat8SeasonAVG"]
                ##5game
                del home["VisBat8fiveGameSO"]
                del home["VisBat8fiveGameSingles"]
                del home["VisBat8fiveGameDoub"]
                del home["VisBat8fiveGameTrip"]
                del home["VisBat8fiveGameHR"]
                del home["VisBat8fiveGameHits"]
                del home["VisBat8fiveGameAB"]
                del home["VisBat8fiveGameWalk"]
                del home["VisBat8fiveGameAVG"]
                del home["VisBat8gameSO"]
                del home["VisBat8gameSingles"]
                del home["VisBat8gameDoub"]
                del home["VisBat8gameTrip"]
                del home["VisBat8gameHR"]
                del home["VisBat8gameHits"]
                del home["VisBat8gameAB"]
                del home["VisBat8gameWalk"]
                del home["VisBat9Pos"]
                del home["VisBat9SeasonSO"]
                del home["VisBat9SeasonSingles"]
                del home["VisBat9SeasonDoub"]
                del home["VisBat9SeasonTrip"]
                del home["VisBat9SeasonHR"]
                del home["VisBat9SeasonHits"]
                del home["VisBat9SeasonAB"]
                del home["VisBat9SeasonWalk"]
                del home["VisBat9SeasonAVG"]
                ##5game
                del home["VisBat9fiveGameSO"]
                del home["VisBat9fiveGameSingles"]
                del home["VisBat9fiveGameDoub"]
                del home["VisBat9fiveGameTrip"]
                del home["VisBat9fiveGameHR"]
                del home["VisBat9fiveGameHits"]
                del home["VisBat9fiveGameAB"]
                del home["VisBat9fiveGameWalk"]
                del home["VisBat9fiveGameAVG"]
                del home["VisBat9gameSO"]
                del home["VisBat9gameSingles"]
                del home["VisBat9gameDoub"]
                del home["VisBat9gameTrip"]
                del home["VisBat9gameHR"]
                del home["VisBat9gameHits"]
                del home["VisBat9gameAB"]
                del home["VisBat9gameWalk"]
                ##### winner predicter
                del winPredict["GameID"]
                del winPredict["year"]
                del winPredict["Date"]
                del winPredict["VisTeam"]
                del winPredict["HomeTeam"]
                del winPredict["StartTime"]
                del winPredict["GameLoc"]
                del winPredict["VisFinalScore"]
                del winPredict["HomeFinalScore"]
                del winPredict["VisStartPit"]
                del winPredict["HomeStartPit"]
                del winPredict["VisBat1"]
                del winPredict["VisBat1gameSO"]
                del winPredict["VisBat1gameSingles"]
                del winPredict["VisBat1gameDoub"]
                del winPredict["VisBat1gameTrip"]
                del winPredict["VisBat1gameHR"]
                del winPredict["VisBat1gameHits"]
                del winPredict["VisBat1gameAB"]
                del winPredict["VisBat1gameWalk"]
                del winPredict["VisBat2"]
                del winPredict["VisBat2gameSO"]
                del winPredict["VisBat2gameSingles"]
                del winPredict["VisBat2gameDoub"]
                del winPredict["VisBat2gameTrip"]
                del winPredict["VisBat2gameHR"]
                del winPredict["VisBat2gameHits"]
                del winPredict["VisBat2gameAB"]
                del winPredict["VisBat2gameWalk"]
                del winPredict["VisBat3"]
                del winPredict["VisBat3gameSO"]
                del winPredict["VisBat3gameSingles"]
                del winPredict["VisBat3gameDoub"]
                del winPredict["VisBat3gameTrip"]
                del winPredict["VisBat3gameHR"]
                del winPredict["VisBat3gameHits"]
                del winPredict["VisBat3gameAB"]
                del winPredict["VisBat3gameWalk"]
                del winPredict["VisBat4"]
                del winPredict["VisBat4gameSO"]
                del winPredict["VisBat4gameSingles"]
                del winPredict["VisBat4gameDoub"]
                del winPredict["VisBat4gameTrip"]
                del winPredict["VisBat4gameHR"]
                del winPredict["VisBat4gameHits"]
                del winPredict["VisBat4gameAB"]
                del winPredict["VisBat4gameWalk"]
                del winPredict["VisBat5"]
                del winPredict["VisBat5gameSO"]
                del winPredict["VisBat5gameSingles"]
                del winPredict["VisBat5gameDoub"]
                del winPredict["VisBat5gameTrip"]
                del winPredict["VisBat5gameHR"]
                del winPredict["VisBat5gameHits"]
                del winPredict["VisBat5gameAB"]
                del winPredict["VisBat5gameWalk"]
                del winPredict["VisBat6"]
                del winPredict["VisBat6gameSO"]
                del winPredict["VisBat6gameSingles"]
                del winPredict["VisBat6gameDoub"]
                del winPredict["VisBat6gameTrip"]
                del winPredict["VisBat6gameHR"]
                del winPredict["VisBat6gameHits"]
                del winPredict["VisBat6gameAB"]
                del winPredict["VisBat6gameWalk"]
                del winPredict["VisBat7"]
                del winPredict["VisBat7gameSO"]
                del winPredict["VisBat7gameSingles"]
                del winPredict["VisBat7gameDoub"]
                del winPredict["VisBat7gameTrip"]
                del winPredict["VisBat7gameHR"]
                del winPredict["VisBat7gameHits"]
                del winPredict["VisBat7gameAB"]
                del winPredict["VisBat7gameWalk"]
                del winPredict["VisBat8"]
                del winPredict["VisBat8gameSO"]
                del winPredict["VisBat8gameSingles"]
                del winPredict["VisBat8gameDoub"]
                del winPredict["VisBat8gameTrip"]
                del winPredict["VisBat8gameHR"]
                del winPredict["VisBat8gameHits"]
                del winPredict["VisBat8gameAB"]
                del winPredict["VisBat8gameWalk"]
                del winPredict["VisBat9"]
                del winPredict["VisBat9gameSO"]
                del winPredict["VisBat9gameSingles"]
                del winPredict["VisBat9gameDoub"]
                del winPredict["VisBat9gameTrip"]
                del winPredict["VisBat9gameHR"]
                del winPredict["VisBat9gameHits"]
                del winPredict["VisBat9gameAB"]
                del winPredict["VisBat9gameWalk"]
                del winPredict["VisBat1Pos"]
                del winPredict["VisBat2Pos"]
                del winPredict["VisBat3Pos"]
                del winPredict["VisBat4Pos"]
                del winPredict["VisBat5Pos"]
                del winPredict["VisBat6Pos"]
                del winPredict["VisBat7Pos"]
                del winPredict["VisBat8Pos"]
                del winPredict["VisBat9Pos"]
                del winPredict["HomeBat1"]
                del winPredict["HomeBat1gameSO"]
                del winPredict["HomeBat1gameSingles"]
                del winPredict["HomeBat1gameDoub"]
                del winPredict["HomeBat1gameTrip"]
                del winPredict["HomeBat1gameHR"]
                del winPredict["HomeBat1gameHits"]
                del winPredict["HomeBat1gameAB"]
                del winPredict["HomeBat1gameWalk"]
                del winPredict["HomeBat2"]
                del winPredict["HomeBat2gameSO"]
                del winPredict["HomeBat2gameSingles"]
                del winPredict["HomeBat2gameDoub"]
                del winPredict["HomeBat2gameTrip"]
                del winPredict["HomeBat2gameHR"]
                del winPredict["HomeBat2gameHits"]
                del winPredict["HomeBat2gameAB"]
                del winPredict["HomeBat2gameWalk"]
                del winPredict["HomeBat3"]
                del winPredict["HomeBat3gameSO"]
                del winPredict["HomeBat3gameSingles"]
                del winPredict["HomeBat3gameDoub"]
                del winPredict["HomeBat3gameTrip"]
                del winPredict["HomeBat3gameHR"]
                del winPredict["HomeBat3gameHits"]
                del winPredict["HomeBat3gameAB"]
                del winPredict["HomeBat3gameWalk"]
                del winPredict["HomeBat4"]
                del winPredict["HomeBat4gameSO"]
                del winPredict["HomeBat4gameSingles"]
                del winPredict["HomeBat4gameDoub"]
                del winPredict["HomeBat4gameTrip"]
                del winPredict["HomeBat4gameHR"]
                del winPredict["HomeBat4gameHits"]
                del winPredict["HomeBat4gameAB"]
                del winPredict["HomeBat4gameWalk"]
                del winPredict["HomeBat5"]
                del winPredict["HomeBat5gameSO"]
                del winPredict["HomeBat5gameSingles"]
                del winPredict["HomeBat5gameDoub"]
                del winPredict["HomeBat5gameTrip"]
                del winPredict["HomeBat5gameHR"]
                del winPredict["HomeBat5gameHits"]
                del winPredict["HomeBat5gameAB"]
                del winPredict["HomeBat5gameWalk"]
                del winPredict["HomeBat6"]
                del winPredict["HomeBat6gameSO"]
                del winPredict["HomeBat6gameSingles"]
                del winPredict["HomeBat6gameDoub"]
                del winPredict["HomeBat6gameTrip"]
                del winPredict["HomeBat6gameHR"]
                del winPredict["HomeBat6gameHits"]
                del winPredict["HomeBat6gameAB"]
                del winPredict["HomeBat6gameWalk"]
                del winPredict["HomeBat7"]
                del winPredict["HomeBat7gameSO"]
                del winPredict["HomeBat7gameSingles"]
                del winPredict["HomeBat7gameDoub"]
                del winPredict["HomeBat7gameTrip"]
                del winPredict["HomeBat7gameHR"]
                del winPredict["HomeBat7gameHits"]
                del winPredict["HomeBat7gameAB"]
                del winPredict["HomeBat7gameWalk"]
                del winPredict["HomeBat8"]
                del winPredict["HomeBat8gameSO"]
                del winPredict["HomeBat8gameSingles"]
                del winPredict["HomeBat8gameDoub"]
                del winPredict["HomeBat8gameTrip"]
                del winPredict["HomeBat8gameHR"]
                del winPredict["HomeBat8gameHits"]
                del winPredict["HomeBat8gameAB"]
                del winPredict["HomeBat8gameWalk"]
                del winPredict["HomeBat9"]
                del winPredict["HomeBat9gameSO"]
                del winPredict["HomeBat9gameSingles"]
                del winPredict["HomeBat9gameDoub"]
                del winPredict["HomeBat9gameTrip"]
                del winPredict["HomeBat9gameHR"]
                del winPredict["HomeBat9gameHits"]
                del winPredict["HomeBat9gameAB"]
                del winPredict["HomeBat9gameWalk"]
                del winPredict["HomeBat1Pos"]
                del winPredict["HomeBat2Pos"]
                del winPredict["HomeBat3Pos"]
                del winPredict["HomeBat4Pos"]
                del winPredict["HomeBat5Pos"]
                del winPredict["HomeBat6Pos"]
                del winPredict["HomeBat7Pos"]
                del winPredict["HomeBat8Pos"]
                del winPredict["HomeBat9Pos"]
                
                if testyrStart <= year <= testyrEnd:
                    retTestScore.append(vis)
                    retTestScore.append(home)
                    retTestWinner.append(winPredict)
                    retTestScoreY.append(visY)
                    retTestScoreY.append(homeY)
                    retTestWinnerY.append(winner)
                elif valyrStart <= year <= valyrEnd:
                    retValScore.append(vis)
                    retValScore.append(home)
                    retValWinner.append(winPredict)
                    retValScoreY.append(visY)
                    retValScoreY.append(homeY)
                    retValWinnerY.append(winner)
                else:
                    retTrainingScore.append(vis)
                    retTrainingScore.append(home)
                    retTrainWinner.append(winPredict)
                    retTrainingScoreY.append(visY)
                    retTrainingScoreY.append(homeY)
                    retTrainWinnerY.append(winner)
                    
        return retTrainingScore, retTrainingScoreY, retValScore, retValScoreY, retTestScore, retTestScoreY, retTrainWinner, retTrainWinnerY, retValWinner, retValWinnerY, retTestWinner, retTestWinnerY